### ISSUE TITLE
can i know whether we can implement in node.js .

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [anishkny/playwright-test-coverage-demo#1]
Hii, anishkny
 
 My project was based on NodeJS i am trying to implement "Playwright-test-coverage" using your dependency. Can u help how to do it. If u have any example can u share me. Thanking you in advance.

**Comment by anishkny** [comment]
@Lakshmi-Yaswanth this [blog post](https://dev.to/anishkny/code-coverage-for-a-nextjs-app-using-playwright-tests-18n7) explains how to use `playwright-test-coverage` in detail. Please take a look, and let me know if you have questions. Best luck!

**Comment by vishalshrm539** [comment]
@anishkny Does this work with React? If it does then could you please provide an example as when I tried it with React, it isn't working properly.

**Comment by anishkny** [comment]
@vishalshrm539 The current repo [anishkny/playwright-test-coverage-demo](https://github.com/anishkny/playwright-test-coverage-demo) shows how to use this plugin with [Next.js ](https://nextjs.org/) which uses React underneath.

Fundamentally, you have to instrument your frontend code using [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) as noted in the [prerequisites](https://github.com/anishkny/playwright-test-coverage#prerequisites).

Could you provide a repo with the simplest possible reproduction steps?

**Comment by vishalshrm539** [comment]
@anishkny Thanks for replying!
I'm having a React project doesn't use Babel and rather uses Webpack. My query is- is it possible for me to add an istanbul pugin in my setting(i.e. Webpack) to be able to instrument my code files for coverage? 

I don't want to use `react-app-rewired` which is an alternative I believe.

And I think Playwright does offer `Coverage` out of the box using startJSCoverage, etc. APIs. Is it possible to get the coverage from those APIs and read them with istanbul? Is there an example for this that I can follow if at all it exists?

**Comment by anishkny** [comment]
Try instrumenting your code using [istanbul-instrumenter-loader](https://v4.webpack.js.org/loaders/istanbul-instrumenter-loader/). Somehow, you would need to instrument your code using `istanbul`.
