### ISSUE TITLE
How to implements in angular project?

### ISSUE THREAD

**Issue by anfruiz** [anishkny/playwright-test-coverage-demo#2]
Hi! I have an angular project and I test it with playwright. I want to implement this library but I don't know how tu set up babel. Do you have an example with angular? Or I can't implement?

**Comment by anishkny** [comment]
@anfruiz Hi sorry for the late reply. 

As documented, this plugin assumes that the code has been instrumented with [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) during the build process. I am not sure how to achieve that with Angular.
